import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {SheetProvider} from "@/providers/sheet-provider"

import {
  ClerkProvider
} from '@clerk/nextjs'
import { QueryProvider } from "@/providers/query-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <SheetProvider />
        {children}
        </QueryProvider>
        </body>
    </html>
    </ClerkProvider>
  );
}
